#!/bin/bash

# make virtualenv and install deps
virtualenv -p /usr/bin/python3 venv
source venv/bin/activate
pip install -r requirements.txt

# copy consumers.example.yml to consumers.yml if it doesn't exist already
if [ ! -f consumers.yml ]; then
  cp consumers.example.yml consumers.yml
fi
